multigeiger/multigeiger.ino
SBM20: the correct conversion factor was not set up due to a code bug
Si22G: was not dealt with at all in previous code.
now correct dummy code is in place, but the conversion factor value
needs to be fixed still, see XXX FIXME (issue #20).
=> fix SBM20 conversion factor selection, support Si22G GM tube

Debug_Sketch/Debug_Sketch.ino
the debug sketch seems to have started as a 1:1 copy of the (by-then) multigeiger.ino.
i don't think it is necessary to duplicate all the infos in the header as this is just for debugging.
but, for formal/legal reasons, I added a similar, but shorter copyright/licensing note.
=> debug sketch: add licensing, remove duplicate header comments

README.md, multigeiger/userdefines-example.h, platformio-example.ini
no need to duplicate them in the README,
people need to read and edit the config files anyway.
=> move explanations from README to config files, fixes #51

multigeiger/multigeiger.ino
(see also current conversion factor of Si22G tube, we also use 0.0 there, for the same reason)
=> unknown tube: use 0.0 conversion factor

multigeiger/multigeiger.ino
see https://github.com/espressif/arduino-esp32/issues/2422
(and it seems they really had a typo "temprature" in the API function while it was supported...)
=> the internal temp sensor is obsolete / unsupported

multigeiger/multigeiger.ino
output generated by first changeset:
```
GMC_counts Time_difference Count_Rate Dose_Rate HV Pulses Accu_GMC Accu_Time Accu_Rate Accu_Dose
[Counts]            [ms]      [cps]   [uSv/h]       [-] [Counts]      [ms]     [cps]   [uSv/h]
-------------------------------------------------------------------------------------------------------------------------------------------
90            9995   9.004502  0.000000         1       90      9995  9.004502  0.000000
100            9440  10.593221  0.000000         1      190     19435  9.776177  0.000000
99            9736  10.168447  0.000000         1      289     29171  9.907100  0.000000
89            9662   9.211344  0.000000         1      378     38833  9.733989  0.000000
100           10223   9.781864  0.000000         1      478     49056 …
```
=> Logging: fixed output format / consistency, fixes #81

multigeiger/multigeiger.ino
if we want the speaker tick, the tick generation does a delay of 4ms total.
else we need to do an alternative delay of 4ms (so that the LED is on
for 4ms) - but ONLY if the LED is enabled.
this fixes 2 inconsistent conditions for speaker and LED.
=> LED/speaker tick: fix conditions for alternative delay

multigeiger/multigeiger.ino
Some windows terminal programs have problems with only LF, so we send both CR and LF.
The long string with dashes is moved to flash and defined as variable.
=> Send CR and LF on serial

multigeiger/multigeiger.ino, multigeiger/userdefines-example.h
if one experiments with a not-yet-supported tube, one wants to
select the entry at index 0 in the tubes array (which is "Radiation
unknown" with a CPM to uSv/h conversion factor of 0.0).
Not sure whether sensor.info and other sites can deal yet with that
sensor type (if values are accidentally submitted), but I guess they
should ignore type 0 tube measurements.
Of course one should usually not submit measurements while
experimenting anyway.
=> add TUBE_UNKNOWN 0 to have a specific value for experimenting

.readthedocs.yml
as we use docs/source/... and not docs/..., we need that.
=> add config file for readthedocs

README.md
1. Eine "U8g2 von Oliver, Version 2.16.14" gibt es nicht. 2.26.14 dagegen schon und das Projekt compiliert damit.
2. Link für die Heltec Board-Repositories in die Doku gepackt. Wo man das herbekommt, ist sonst nicht offensichtlich.
=> improved documentation for people without prior Arduino/ESP experience

multigeiger/multigeiger.ino
We now send more data to the servers:
hv_pulses : number of HV pulses needed to charge (sent mainly für debug reasons)
counts : absolute number of geiger counts counted during sample time
sample_time_ms : expired time for this counts.
counts and sample_time are for statistics and easier error analysis (in the future).
=> Send additional data to servers and do a little cleanups

multigeiger/multigeiger.ino, multigeiger/userdefines-example.h
- printf-style call
- only outputs for level >= log_level
- levels: DEBUG, INFO, WARNING, ERROR, CRITICAL, NOLOG
- internally prepends "GEIGER: " to differentiate our output from other
- adds correct line endings by using Serial.println()
not tested yet.
=> new log(level, format, ...) function, fixes #161

README-en.rst, docs/source/index.rst
this is about how a project README should look like, IMHO.
it should contain enough information for the reader to decide whether
this is the project they searched for.
but it should not be TL;DR (== too long; didn't read).
thus, it should NOT contain detailled installation and configuration
docs (that stuff belongs into the extensive docs the README links to).
this README has 2 uses / functions:
- being included as introduction into the long readthedocs.io based docs
- being shown on github (after review / community decision)
this avoids duplication and eases future changes/updates.
=> add a basic, short README in English

.bumpversion.cfg, docs/source/changes.rst, docs/source/conf.py, multigeiger/multigeiger.ino, multigeiger/version.h
this tool can be used to automatically update the version numbers in misc. files (currently we have 3 places), so that this does not have to be done manually.
also it adds a corresponding git tag and, as configured now, signs the tag.
this avoids mistakes like forgetting some places, doing inconsistent updates or forgetting to set a tag.
=> use bump2version

multigeiger/display.cpp, multigeiger/loraWan.cpp, multigeiger/multigeiger.ino, multigeiger/transmission.cpp, multigeiger/userdefines-example.h, multigeiger/utils.cpp, multigeiger/utils.h, multigeiger/webconf.cpp, multigeiger/webconf.h
lorawan.cpp:
- only compile, if CPU==STICK, i.e if we have LoRa Hardware
- fetch LoRa credentials from config variables
multigeiger.ino:
- use config variables instead of userdefines
transmission.cpp:
- replace SEND2LORA by CPU==STICK
- use config variables to decide where to send
- send to LoRa only, if LoRa credentials are known
webconf.cpp
- add all config variable to web page
- do restart after saving config
userdefines-example.h
- remove now unnecessary #defines
=> Use webpage to to set configuration, fixes #140

multigeiger/display.cpp
the old code put the terminating \0 at the wrong place,
so the result was 9 chars wide instead of the desired 8.
the new code avoids this issue and is also simpler.
=> fix/refactor clearDisplayLine

multigeiger/multigeiger.ino, multigeiger/timers.cpp, multigeiger/timers.h, multigeiger/tube.cpp, multigeiger/tube.h
This does all HV charging via a timer driven ISR.
This fixes #192, but in an improved way:
Just doing a HV charge pulse "every second" is not good enough:
- if radiation-caused discharging and discharging caused by other leaks are low, a pulse every second is more than needed. No big problem, just drawing more power than needed.
- if radiation or leaks are high, doing only 1 pulse per second is not enough, so we need to adapt to not let the HV voltage break down.
The code adapts to this by targeting a 2-pulse recharge.
Due to the way we charge, we always will have 1 charge pulse - no matter whether we actually needed to charge or not. But 2 pulses are only needed if we really needed to charge. Thus the code targets doing 2 pulses.
If less than 2 pulses are needed, we are maybe charging …
=> timer-driven adaptive recharging

multigeiger/transmission.cpp
this is practically tested using a http: as well as a https: toilet URL, it worked for both.
=> fix transmission to http: URLs, fixes #262

multigeiger/multigeiger.ino, multigeiger/speaker.cpp, multigeiger/speaker.h, multigeiger/timers.cpp, multigeiger/timers.h, multigeiger/tube.cpp
hardware PWM for sound (ticks and tones).
this is now a hw timer interrupt driven sequencer which uses hw PWM for sound output. :-)
high volume: drives the PWM outputs in a complementary way
low volume: one PWM output, other output fixed low.
thus, output power (== volume) should be as before.
the high-pitch geiger tick is now directly initiated from ISR code.
there is also the capability for a low-pitch "tock" now, can be used for debugging.
the main loop only spins once a second now.
=> timer-driven sequencer, hw PWM sound, fixes #35

README.md, multigeiger/multigeiger.ino, multigeiger/thp_sensor.cpp, platformio-example.ini
After wondering some time why my THP stopped working after the FW update, I noticed it's an BME680 board. This PR adds BME680 lib to allow transparent readout of THP only from BME680 as well as from BME280.
Future option to read and log gas resistance value for air quality changes not considered here.
=> add bme680 library for basic THP readout of BME680

docs/source/index.rst, docs/source/usage.rst
i made this using the bigger display on the wifi-only board.
@rexfue can you check whether the description is ok for the wifi/lora board also?
=> docs: add usage chapter, description of OLED display, fixes #264

multigeiger/speaker.cpp
the compiler warning ("... is used before initialized") is a false positive,
but let's just initialize the vars to get rid of it.
=> speaker: avoid compiler warning

docs/source/usage.rst, multigeiger/multigeiger.ino
in case of some unsuccessful transmission attempt, the error code was
only shown for a short time and then replaced by idle status again.
fixed, now the error code is shown until the transmission is retried.
also removed some unneeded status display related code for BT and LoRa,
the initial state is "NODISPLAY" anyway.
=> status display: keep showing transmission errors

multigeiger/multigeiger.ino, multigeiger/tube.cpp
it could happen that display() was called before there was any GM event.
in that case, there were 2 timestamps initialized to millis() at different
times in program setup / subsystem setup time and dt could become
negative.
removed the millis() and just used 0 to initialize both.
check for the special condition and do not display/log/transmit anything
in that case.
=> fix race condition, fixes #286

README-de.md
Der Abschnitt mit den allgemeinen Eigenschaften des Multigeigers ist bereits in den neuen Docs in Deutsch und in Englisch vorhanden, daher hier entfernt.
Stattdessen einen Hinweis hinzugefügt, dass nach und nach aller Content dorthin umziehen sollte.
Das kann "häppchenweise" geschehen:
- hier entfernen
- dort hinzufügen (docs/source/*.rst - in Englisch) und auf transifex auf Deutsch übersetzen
- sphinx / transifex workflow siehe developer docs
=> legacy README: remove duplicate content, add link to new docs

docs/source/usage.rst
to make it identical to the line at point 3 (TTN) and to make it clearer
=> changed 'not configured / enabled' to 'not configured, not enabled'

multigeiger/loraWan.cpp, multigeiger/loraWan.h, multigeiger/multigeiger.ino, multigeiger/transmission.cpp, multigeiger/transmission.h
This PR has two distinct changesets.
- Add LMIC polling from loop (https://github.com/ecocurious2/MultiGeiger/commit/134159f33534ce9a21f904499fc5aed76661cca7). The LMIC requires continous polling while it's active; "activity" can go on a long time, because it's based on network activity and internal state. Polling the LMIC takes essentially no time if there's nothing in the queue, so this will not disturb things in the rest of the app.
- Work around LMIC bug 677 (https://github.com/ecocurious2/MultiGeiger/commit/b8d13b5072a59881cd0569418420debd454abc99). The lack of polling uncovered another problem, which is that the LMIC was not checking all the important flags to prevent transmitting while the LMIC is busy. The correction prevent that. The change will be redundant once the LMIC …
=> Fix #373: Improve LoRaWAN stability

README.rst
these docs were integrated into the *.rst docs and then deleted.
=> remove 404 links to deleted docs

multigeiger/speaker.cpp
I've seen a traceback pointing to an MCPWM issue
and found that this member of the struct has not been
initialized yet.
=> speaker: init "duty_mode" member in MCPWM config

multigeiger/thp_sensor.cpp, platformio-example.ini
BME680 I2C address defines were changed in 'bme68x_defs.h' from Adafruit BME680 lib V2.0.0 to:
BME68X_I2C_ADDR_LOW / _HIGH
instead of _PRIMARY / _SECONDARY
Fixed here.
=> Fix Adafruit BME680 lib V2.0 #macro name change

docs/source/changes.rst, docs/source/usage.rst, locales/de/LC_MESSAGES/changes.po, locales/de/LC_MESSAGES/usage.po, multigeiger/webconf.cpp
The config page and the docs referred to `sensors.community`, which is a different service.
=> Fix sensor.community domain

multigeiger/ble.cpp, platformio-example.ini
Swapped BLE management from Arduino to [NimBLE](https://github.com/h2zero/NimBLE-Arduino) to save RAM and flash.
Changes running locally for a while already under 1.15-dev. Now ported to 1.16-dev.
Includes changes required for Adafruit BME680 V2.0.0.
Before:
RAM:   [==        ]  20.4% (used 66744 bytes from 327680 bytes) 
Flash: [=====     ]  52.4% (used 1752965 bytes from 3342336 bytes)
After:
RAM:   [==        ]  18.9% (used 62032 bytes from 327680 bytes) 
Flash: [====      ]  40.1% (used 1340817 bytes from 3342336 bytes)
=> BLE via NimBLE-Arduino lib

multigeiger/ble.cpp
Clean & build, only remaining warnings are from espressif framework
```
Compiling .pio\build\geiger\FrameworkArduino\esp32-hal-timer.c.o
C:\users\tjalf\.platformio\packages\framework-arduinoespressif32\cores\esp32\esp32-hal-spi.c: In function 'spiTransferBytesNL':
C:\users\tjalf\.platformio\packages\framework-arduinoespressif32\cores\esp32\esp32-hal-spi.c:922:39: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
uint8_t * last_out8 = &result[c_longs-1];
^
C:\users\tjalf\.platformio\packages\framework-arduinoespressif32\cores\esp32\esp32-hal-spi.c:923:40: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
uint8_t * last_data8 = &last_data;
^
Compiling .pio\build\geiger\FrameworkArduino\esp32-hal-touch.c.o
```
=> Removed NimNLE compiler warnings

multigeiger/display.cpp, multigeiger/display.h, multigeiger/multigeiger.ino
Casting brackets misplaced on TimeSec for displaying current uptime.
All variables for seconds changed to "unsigned"
=> fix uptime display - casting brackets
