ecocurious2/MultiGeiger

- multigeiger/multigeiger.ino
- use sprintf instead of home grown formatting
(code uses sprintf elsewhere anyway)
- added some blanks in src for better readability
- fixed font size description in comment
> refactor OLED functions

- multigeiger/multigeiger.ino
trivial change, no code changes.
please merge quickly.
also, check if your editor has a setting to strip trailing whitespace automatically on save.
> remove trailing whitespace

- multigeiger/multigeiger.ino
- multigeiger/userdefines-example.h
As discussed, let's have the source in English.
> Language consistency

- README.md
- changelog.md
- multigeiger/multigeiger.ino
- multigeiger/version.h
- HV will be pulsed ever second independent of geiger pulses
- geiger count rate will be calculated and displayed every 10sec
- struct for the different tubes 
- multiple send2xxx() now in one send2http()
- a few changes in Readme ( especially concerning the userdef-example and platformio-example)
- history in version.h  adapted
> hv pulse every sec, display every 10sec

- multigeiger/multigeiger.ino
- multigeiger/userdefines-example.h
- multigeiger/version.h
- platformio-example.ini
also some slight formatting adjustments, grammar fixes.
> fix typos in src comments and changelog

- Debug_Sketch/Debug_Sketch.ino
- README.md
- multigeiger/multigeiger.ino
> use "Simple Multi-Geiger" everywhere as the project name

- README.md
On special request of Nicola (original author of this section).
It's worse now, but that is Nicola's problem now. :-P
> Revert my changes to the README's intro section.

- multigeiger/multigeiger.ino
and also how they were determined / how they are computed.
> add a FIXME comment asking for sources for the conversion factors

- multigeiger/multigeiger.ino
also: move some not so timing critical stuff to the end of the loop.
> only reset isr_GMC_counts if the display will be updated, fixes #101

- multigeiger/multigeiger.ino
thanks for Juergen for determining the factor!
@WwwBoehriDe please review, is my comment correct like that?
> correct Si22G conversion factor, fixes #20

- multigeiger/multigeiger.ino
> check for time_difference == 0 added

- README.md
fixes #79 
I guess, we could do a release for Freiburg now  -  1.10
> SSID explanation; citysensor.de

- .gitignore
- multigeiger/multigeiger.ino
- multigeiger/userdefines-example.h
- multigeiger/version.h
- platformio-example.ini
- fixed problem with SOFTWARE VERSION on LoRa code. Its's now 2 bytes long.
- change defaults in userdefines-example 
- added defines in platform-example.ini
> Wireless Stick (LoRa) display fixed

- .gitignore
- multigeiger/userdefines-example.h
in user defines-example.h added spaces after //
> spaces_after_comment_mark

- platformio-example.ini
Added the needed libraries to the platformio based systems to automatically pull them
> Adapting the platformio.ini to pull all dependencies

- multigeiger/multigeiger.ino
also:
- add a constant MAX_CHARGE_PULSES
- lowered MAX_CHARGE_PULSES from 1000 to 333 (so it is << 1s as expected by main loop recharge)
- cosmetic changes (3rd commit)
> output error msg on Serial if HV charging fails

- multigeiger/multigeiger.ino
- multigeiger/version.h
> Simple OTA

- multigeiger/multigeiger.ino
- multigeiger/version.h
revert own implementation, re-use code from IotWebConf
docs coming in next PR.
> OTA updates based on IotWebConf

- multigeiger/multigeiger.ino
I found IMHO a better way to set the default thingName
> Better way to set thingName

- multigeiger/multigeiger.ino
The conversion factors retaken from the data sheets
Cosmetic change (char * -> char*)
> Explain conversion factor

- multigeiger/multigeiger.ino
remove "F(" at literal Strings  -> ESP32 puts const char * and literal strings in flash by default
changed log strings to "const char*"
fixes #85
> tag log output with "GEIGER: "

- changelog.md
- multigeiger/multigeiger.ino
doing final tests, will create a github release afterwards...
> Release V1.12.0

- .gitignore
- docs/Makefile
- docs/make.bat
- docs/source/conf.py
- docs/source/index.rst
```
pip3 install --user sphinx  # or any other way to install, see http://www.sphinx-doc.org/
cd docs
make html
```
> basic sphinx docs infrastructure, see #163

- multigeiger/multigeiger.ino
There are BME280 boards with different addresses (0x76 and 0x77). Try to init the BME280 on both addresses.
> try both adresses of BME280

- docs/source/development.rst
some links, some new content, better formatting.
> improve development docs

- README.md
also:
- fix grammar error
- try not to repeat things
- as this is the multigeiger readme, first tell what multigeiger is,
then tell about ecocurious and community aspects.
- do not use future or present tense when stuff is already done
- add some line breaks
> include infos about project name, fixes #121

- multigeiger/multigeiger.ino
lots of cleanups, guess best reviewed by looking at the individual commits.
> multigeiger cleanups

- .travis.yml
- multigeiger/chkhardware.cpp
- multigeiger/chkhardware.h
- multigeiger/display.cpp
- multigeiger/display.h
- multigeiger/loraWan.cpp
- multigeiger/multigeiger.ino
- multigeiger/switches.cpp
- multigeiger/switches.h
- multigeiger/transmission.cpp
- multigeiger/transmission.h
- multigeiger/userdefines-example.h
- multigeiger/webconf.cpp
- multigeiger/webconf.h
- platformio-example.ini
test, if pin 26 (LoRa DIO) is low. If yes, then it is LoRa hardware.
Change in  every file the "#if CPU == STICK" to "if (haveLoRa ) {}"
> check if LoRa chip or not by hardware

- docs/source/development.rst
how to create and test binaries, IDE settings, ...
Fixes #235.
> docs: update development/release docs

- multigeiger/multigeiger.ino
> slow down main loop

- multigeiger/display.cpp
- multigeiger/display.h
- multigeiger/multigeiger.ino
update display.cpp 
- new font for status line (u8x8 uses 8px character width anyway), 
- prepare for BLE connectivity, 
- changed symbol CPS to CPM
> display.cpp - new font for status, prepare BLE connectivity, CPS->CPM

- multigeiger/display.cpp
hooked up the Wireless Stick geiger and did the font & BLE logo adaptions also for isLoraBoard.
> display.cpp adaptions also for Lora board

- multigeiger/display.cpp
- multigeiger/display.h
- multigeiger/multigeiger.ino
- multigeiger/transmission.cpp
fixes #257. 
slightly improves on #201 and #202.
> implement status display

- multigeiger/transmission.cpp
kind of trivial, but not practically tested yet.
> check for http transmission errors, update status, fixes #265

- multigeiger/transmission.cpp
- use http for now, except for testing
- generalized custom server
- added comments about toilet usage :-)
> transmission: http, toilet, custom server

- multigeiger/loraWan.cpp
- multigeiger/multigeiger.ino
- multigeiger/userdefines-example.h
- multigeiger/webconf.cpp
> Defines cleanup

- multigeiger/transmission.cpp
> show lora error on status display

- multigeiger/display.cpp
fixes #299 
fixes #290 
fixes #298
> display cleanup

- multigeiger/multigeiger.ino
- multigeiger/transmission.cpp
- multigeiger/transmission.h
> check wifistatus in transmissions

- multigeiger/display.cpp
- multigeiger/display.h
- multigeiger/multigeiger.ino
- multigeiger/transmission.cpp
pulled out from ble_connectivity PR, as out of scope there
> small changes to display, displaystatus

- .tx/config
- docs/source/conf.py
- docs/source/development.rst
- locales/de/LC_MESSAGES/authors.po
- locales/de/LC_MESSAGES/changes.po
- locales/de/LC_MESSAGES/development.po
- locales/de/LC_MESSAGES/faq.po
- locales/de/LC_MESSAGES/index.po
- locales/de/LC_MESSAGES/resources.po
- locales/de/LC_MESSAGES/usage.po
> translated docs

- multigeiger/ble.cpp
- multigeiger/ble.h
- multigeiger/multigeiger.ino
- multigeiger/switches.cpp
- multigeiger/switches.h
- multigeiger/userdefines-example.h
- multigeiger/webconf.cpp
- multigeiger/webconf.h
Okay, here's a first BT BLE PR. I've marked it as draft at first, although it runs on both my test devices, on Lorastick with BME680 and one Wifi Stick 32. Did some further minor changes, e.g.
- rename "display" to "publish", as it also sends to BT
- if new status change, push directly to display
> BLE connectivity

- multigeiger/multigeiger.ino
> do async NTP/clock setup, fixes #316

- multigeiger/display.cpp
only changed for the big display, small display left "as is".
> Uncrowd start screen

- docs/source/resources.rst
- multigeiger/multigeiger.ino
also:
- updated links
- added wireless stick link
- remove blog posts and links to older lora hw
> moved links to docs -> resources, fixes #223

- platformio-example.ini
incompatible changes break our build.
> don't use IotWebConf 3.0.0 yet, see #357

- .github/workflows/ci.yml
for now, just the astyle checker.
> add github ci workflow

- .tx/config
- locales/de/LC_MESSAGES/about.po
> transifex: add resource for "about"

- misc/arduino-esp32/partition-menu-1.0.5.diff
- misc/arduino-esp32/partition-menu-1.0.5.txt
> restore partition scheme menu for arduino-esp32 1.0.5

- multigeiger/webconf.cpp
- platformio-example.ini
Tested with WiFi-Kit and WiFi-Stick hardware -> works.
Also, OTA update works.
> uses iotwebconf 3.0.2

- multigeiger/log.cpp
- multigeiger/log_data.cpp
- multigeiger/log_data.h
- multigeiger/loraWan.cpp
- multigeiger/multigeiger.ino
- more formatting consistency
- add timestamp
- add t/h/p to rightmost columns
- repeat header output for better readability
Fixes #410.
> improve data logging

- multigeiger/speaker.cpp
inspired by #435 - i just wanted to actually have the alternative implementation i was discussing there in a PR, so we can discuss more specifically, including line numbers.
@t-pi if you see a problem here, tell me the sequence of line numbers that leads to the problem.
> audio isr fixes

- multigeiger/multigeiger.ino
- multigeiger/speaker.cpp
- multigeiger/speaker.h
- multigeiger/userdefines-example.h
- multigeiger/webconf.cpp
- multigeiger/webconf.h
- Some optimizations to the sound sequencer
- Added alarm sequence & function
- Added userdefines.h parameters for enable and threshold
- Added IotWebConf parameters for enable and threshold
- Alarm will sound once every 10 s (every ```publish```) if 
- accumulated dose rate > set threshold (default 0.5 µSv/h)
- current dose rate > 3x accumulated dose rate
> Local alarm compile
